### ISSUE TITLE
app not working

### ISSUE THREAD

**Issue by schrodog** [Saren-Arterius/google-chinese-handwriting-ime#3]
when I load window, the webpage keep reloading iteself, toggling "is_input_active" attribute in webpage

**Comment by Saren-Arterius** [comment]
It seems that this app has caught Google's attention. I have fixed it, I don't know how long it could last.
https://github.com/Saren-Arterius/google-chinese-handwriting-ime/commit/0681621e91c6f470c5044b23701c61aecdf41c40

Please test it and report if it works or not.

**Comment by schrodog** [comment]
Right now it is working. Maybe in long term we should not rely on 3rd party handwriting system, but develop our own

**Comment by Saren-Arterius** [comment]
I will need a research team or few years 😂😂

在 2018年10月29日週一 19:37，schrodog <notifications@github.com> 寫道：

**Comment by schrodog** [comment]
I think handwriting system relies on AI image recognition and stroke pattern order analysis. Maybe there's some open source AI library for this  😃

**Comment by Saren-Arterius** [comment]
> I think handwriting system relies on AI image recognition and stroke pattern order analysis. Maybe there's some open source AI library for this smiley

Dataset is the real problem here :joy:
