### ISSUE TITLE
Installation fails on yarn command

### ISSUE THREAD

**Issue by kcleung** [Saren-Arterius/google-chinese-handwriting-ime#6]
I am running Ubuntu 18.10 on my 15" macbook pro late 2013, and I followed the instructions in README.md

At step 3:

$ yarn

I got this error:

00h00m00s 0/0: : ERROR: There are no scenarios; must have at least one.

so how can we solve this problem?

**Comment by Saren-Arterius** [comment]
You installed the wrong yarn, you need yarn package manager for node

在 2019年1月13日週日 03:29，kcleung <notifications@github.com> 寫道：

**Comment by Saren-Arterius** [comment]
https://github.com/yarnpkg/yarn/issues/2821#issuecomment-284181365

在 2019年1月13日週日 03:30，Saren Arterius <ykmran@gmail.com> 寫道：
